<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>(Multiple/Multivariable) linear regression – Stats knowledgebase</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-e3adbaa939bcd423dddc8c8a834270b4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script>
function goToTab(tabId) {
  const tab = document.getElementById(tabId);
  if (tab) {
    tab.click();
    tab.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }
}
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Stats knowledgebase</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#tldr" id="toc-tldr" class="nav-link active" data-scroll-target="#tldr">TL;DR</a></li>
  <li><a href="#guide" id="toc-guide" class="nav-link" data-scroll-target="#guide">Guide</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">(Multiple/Multivariable) linear regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="tldr" class="level2">
<h2 class="anchored" data-anchor-id="tldr">TL;DR</h2>
<ul>
<li>Check sample size &gt;= 10*num of predictors</li>
<li>Do three diagnostics seen in <a href="#" onclick="goToTab('tabset-1-3-tab'); return false;">When CAN I?</a></li>
<li>Optional: check multicollinearity using <code>car::vif(lm_output) &gt;=10</code> if you care about variable interpretation and contribution (not prediction)</li>
<li>Check manual and adjusted <span class="math inline">\(R^2&gt;&gt;0\)</span></li>
<li>Check the residuals summary has a median close to zero (in units of response var)</li>
<li>Check residual standard error is small for the units and mean of your response variable</li>
<li>Continue looking at traits by following <a href="#" onclick="goToTab('tabset-1-5-tab'); return false;">How to interpret?</a><br>
</li>
<li>When you’re happy with the selected traits, report, use the guide example in <a href="#" onclick="goToTab('tabset-1-6-tab'); return false;">Reporting</a></li>
</ul>
<p>The regression of <span class="math inline">\(Y\)</span> on <span class="math inline">\(x\)</span> is the conditional mean <span class="math inline">\(E(Y|x) = m(x)\)</span>, where <span class="math inline">\(m(x)\)</span> can take any form, but in a linear regression, it takes this form: <span class="math display">\[\begin{gather} E(Y|x) = m(x) = \beta_0 + \sum_{j=1}^k \beta_jg_{j}(x) \text{ and } \\ var(Y|x) = \sigma^2 \end{gather}\]</span> where <span class="math inline">\(\beta_j\)</span> are the coefficients. Performing a regression means estimating <span class="math inline">\(\beta_j, ~ j = 0,..,k\)</span>.</p>
</section>
<section id="guide" class="level2">
<h2 class="anchored" data-anchor-id="guide">Guide</h2>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">Common phrases</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">When?</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">When CAN I?</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">How to assess?</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false" href="">How to interpret?</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false" href="">Reporting</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-7-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-7" role="tab" aria-controls="tabset-1-7" aria-selected="false" href="">R caveats/defaults</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-8-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-8" role="tab" aria-controls="tabset-1-8" aria-selected="false" href="">What now?</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-9-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-9" role="tab" aria-controls="tabset-1-9" aria-selected="false" href="">Maths</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<section id="common-phrases-associated-with-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="common-phrases-associated-with-linear-regression">Common phrases associated with linear regression</h3>
<ul>
<li>Regression in the dictionary means “a return to a former state”</li>
<li>The sentence “regression to the mean” means if a variable is extreme on its first measurement, it will tend to be closer to the average on its second measurement and vice versa</li>
<li>Linear actually means linear in the coefficients, i.e.&nbsp;not necessarily a straight line but a linear combination (i.e an additive function) of complex and non-linear functions of x, with the coefficients ‘out the front’<br>
</li>
<li>Additive function <span class="math inline">\(f\)</span> is such that this holds <span class="math display">\[ f_{v_1+v_2}(x) = f_{v_1}(x) + f_{v_2}(x), \text{ and } f_{c*v_1}(x) = c*f_{v_1}(x) \]</span> where <span class="math display">\[ v_1 = (\beta_0, \beta_1, ..., \beta_k), ~ v_2 = (\alpha_0, \alpha_1, ..., \alpha_k)\]</span> i.e.&nbsp;the coefficients of <span class="math inline">\(f(x)\)</span>.<br>
See <a href="#" onclick="goToTab('tabset-1-9-tab'); return false;">Maths</a> for proof this holds for <span class="math inline">\(E(Y|x) = m(x) = \beta_0 + \sum_{j=1}^k \beta_jg_{j}(x)\)</span></li>
</ul>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<section id="when-do-i-use-a-linear-regression" class="level3">
<h3 class="anchored" data-anchor-id="when-do-i-use-a-linear-regression">When do I use a linear regression?</h3>
<p>(a.k.a what question do I need answering so that the answer is “use a lin regression for that”?)</p>
<ul>
<li>you are interested in inferring a relationship between a variable/trait Y and a (vector of) variable/trait(s)<br>
</li>
<li>you are interested in predicting Y based on a new value of the variable/trait(s)</li>
</ul>
<p>This explanation leads to treating Y as a random variable and x as the known. Y is modelled as a <strong>deterministic</strong> function <span class="math inline">\(m(x)\)</span> plus a mean-zero noise term i.e.&nbsp; the observation <span class="math inline">\((x_i, Y_i)\)</span> satisfies <span class="math inline">\(Y_i = m(x_i) + \epsilon_i\)</span>, where for all <span class="math inline">\(i\)</span>, <span class="math inline">\(\epsilon_i\)</span> are independent, <span class="math inline">\(E(\epsilon_i)=0\)</span> and <span class="math inline">\(var(\epsilon_i)= \sigma^2\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If <span class="math inline">\(var(\epsilon_i)= \sigma_i^2\)</span>, it’s called heteroscedasticity, handling this TBA</p>
</div>
</div>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<section id="when-can-i-use-this-what-needs-to-hold-up-for-me-to-even-think-about-using-it" class="level3">
<h3 class="anchored" data-anchor-id="when-can-i-use-this-what-needs-to-hold-up-for-me-to-even-think-about-using-it">When CAN I use this, what needs to hold up for me to even think about using it?</h3>
<p>We have to check the assumptions hold. The assumptions are:</p>
<ol type="1">
<li>linear model for the mean, i.e.&nbsp;<span class="math inline">\(E(Y|x) = m(x)\)</span> is linear<br>
</li>
<li><span class="math inline">\(var(\epsilon_i)= \sigma^2\)</span> i.e.&nbsp;var is the same for all <span class="math inline">\(i\)</span><br>
</li>
<li>the residue (error, noise) normality assumption of <span class="math inline">\(\epsilon_i \sim N(0, \sigma^2)\)</span> we have to introduce if we would like to know how well our coefficients are estimated (for CIs and testing hypotheses like whether the coeffs differ from 0 i.e.&nbsp;where Y is varying of x)</li>
</ol>
<p>To check these assumptions, you need to fit the model first, and then check the assumptions. For each assumption you do:</p>
<ol type="1">
<li><strong>Plot observed vs fitted values:</strong> each data point is described by the observed <span class="math inline">\(Y_i\)</span> and by the value <span class="math inline">\(m(x_i)\)</span> you have come to i.e.&nbsp;the value on your estimated line), you are hoping to see points scattered randomly along the diagonal line of y = x<br>
</li>
<li><strong>Plot residuals vs fitted values:</strong> each data point is described by the residual — observed <span class="math inline">\(Y_i\)</span> minus <span class="math inline">\(m(x_i)\)</span> — and <span class="math inline">\(m(x_i)\)</span>, you are hoping to see an equal amount of points above and below 0 at similar distances from 0 and spread across the x axis (if that is not the case, plotting residuals vs.&nbsp;a specific independent variable tells you which specific variable needs to be “fixed” e.g., if you see a curve here, you need to add a squared term of this specific variable)<br>
</li>
<li><strong>Plot a normal QQ plot of the residuals</strong>: checks whether the distribution of residuals is <span class="math inline">\(\sim N(0, \sigma^2)\)</span> - you’re hoping to see all the points on the diagonal</li>
</ol>
<p>Note: each <span class="math inline">\(Y_i\)</span> depends on <span class="math inline">\(x_i\)</span>, the normality assumption is per <span class="math inline">\(x_i\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">url</span>(<span class="st">"https://github.com/cran/ElemStatLearn/raw/refs/heads/master/data/prostate.RData"</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> age <span class="sc">+</span> lbph <span class="sc">+</span> svi <span class="sc">+</span> lcp <span class="sc">+</span> gleason <span class="sc">+</span> pgg45, <span class="at">data =</span> prostate)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># looking at 1)</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(lm1), prostate<span class="sc">$</span>lpsa, <span class="at">xlab =</span> <span class="st">"Fitted"</span>, <span class="at">ylab =</span> <span class="st">"Observed"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="dv">0</span>,<span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lin_regression_files/figure-html/lm_diagnostics-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># looking at 2)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(lm1), <span class="fu">residuals</span>(lm1), <span class="at">xlab =</span> <span class="st">"Fitted"</span>, <span class="at">ylab =</span> <span class="st">"Residuals"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lin_regression_files/figure-html/lm_diagnostics-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># I personally like this built-in version of fitted vs observables more, due to</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the fitted curve, you'd want it to follow y = 0 as much as possible (not easy</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># when you have a smaller dataset, then it might be distracting)</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lm1, <span class="dv">1</span><span class="sc">:</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lin_regression_files/figure-html/lm_diagnostics-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># looking at 3)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Q-Q plots compare quantiles of the observed data to the quantiles of your theoretical distribution</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># qqnorm compares to N(0,1)</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">residuals</span>(lm1))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># default distribution based on which the line is drawn is N(0,1)</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># it's just a line that draws through the 1st and 3rd quantile (because we believe</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># that all the points from our data coincide with data points in this distribution, </span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># then so do the quantiles in our data and the theoretical quantiles, and we choose</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># to make a line through those, so that they are not favoured by a different mean/outliers)</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">residuals</span>(lm1))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lin_regression_files/figure-html/lm_diagnostics-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If you care about interpretation of the predictors in this model, you need to check whether there is multicollinearity between the predictors. If any of the predictor’s variance inflation factor is over 10, the more likely multicollinearity is present and that predictor(s) should be dropped -&gt; that decision should be based on more investigation, like pairwise correlation, domain knowledge and/or with a usage of Lasso or Ridge regression TBA.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(lm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  lcavol  lweight      age     lbph      svi      lcp  gleason    pgg45 
2.102650 1.453325 1.336099 1.385040 1.955928 3.097954 2.468891 2.974075 </code></pre>
</div>
</div>
</section>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<section id="how-to-assess-if-my-lin-model-is-likely-a-lin-model" class="level3">
<h3 class="anchored" data-anchor-id="how-to-assess-if-my-lin-model-is-likely-a-lin-model">How to assess if my lin model is likely a lin model?</h3>
<p>Apart from doing everything in <a href="#" onclick="goToTab('tabset-1-3-tab'); return false;">When CAN I?</a>, especially 1), there is also:</p>
<ul>
<li>The residuals summary should have a median around 0 in your reponses’s units, otherwise it might indicate your model is misspecified (should be confirmed with Q-Q plot)<br>
</li>
<li><span class="math inline">\(R^2\)</span>, which is the coefficient of determination, measures the strength of the linear relationship between the traits and outcome and is between 0 and 1 i.e.&nbsp;the proportion of <span class="math inline">\(varY\)</span> that is explained by your estimated m(x); an <span class="math inline">\(R^2&gt;&gt;0\)</span> indicates a closer fit of the model to the data, and the adjusted <span class="math inline">\(R^2\)</span> takes into account irrelevant predictors<br>
</li>
<li>The Residual standard error should be small, close to 0 in your response’s units<br>
</li>
<li>Overall p-value of the F-statistic test should tell you it’s a better model than no model</li>
</ul>
<p>The output: <img src="../../images/lm_summary.png" class="img-fluid" alt="Summary output"></p>
</section>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<section id="how-to-interpret-it-once-i-know-its-a-likely-a-lin-model" class="level3">
<h3 class="anchored" data-anchor-id="how-to-interpret-it-once-i-know-its-a-likely-a-lin-model">How to interpret it once I know it’s a likely a lin model?</h3>
<p>Normally you want to see whether the trait(s) are in a relationship with <span class="math inline">\(Y\)</span>, and you would do so by testing whether the coefficients next to those traits are statistically significantly different from 0.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpsa <span class="sc">~</span> lcavol <span class="sc">+</span> lweight <span class="sc">+</span> age <span class="sc">+</span> lbph <span class="sc">+</span> svi <span class="sc">+</span> lcp <span class="sc">+</span> gleason <span class="sc">+</span> pgg45, <span class="at">data =</span> prostate)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lpsa ~ lcavol + lweight + age + lbph + svi + lcp + 
    gleason + pgg45, data = prostate)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.76644 -0.35510 -0.00328  0.38087  1.55770 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.181561   1.320568   0.137  0.89096    
lcavol       0.564341   0.087833   6.425 6.55e-09 ***
lweight      0.622020   0.200897   3.096  0.00263 ** 
age         -0.021248   0.011084  -1.917  0.05848 .  
lbph         0.096713   0.057913   1.670  0.09848 .  
svi          0.761673   0.241176   3.158  0.00218 ** 
lcp         -0.106051   0.089868  -1.180  0.24115    
gleason      0.049228   0.155341   0.317  0.75207    
pgg45        0.004458   0.004365   1.021  0.31000    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6995 on 88 degrees of freedom
Multiple R-squared:  0.6634,    Adjusted R-squared:  0.6328 
F-statistic: 21.68 on 8 and 88 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If some coefficients are not so different from 0, you might want to consider a simpler model without these traits included, and test whether the two nested models are the same, and then proceed with the simpler one (o/w if they are significantly different, proceed with the more complex model) - see Anova in testing TBA</p>
<p>Whether the intercept is significantly different from 0 or not matters for whatever your model represents i.e.&nbsp;the state of the outcome when all of your traits are 0 <span class="math inline">\(\rightarrow\)</span> I would use this as a reality check</p>
</section>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<p>The report depends on what type your data is and whether it was scaled (affects interpreting coefficients and changes in your outcome), as well as whether your goal is predictions or variable interpretation (affects whether you care about having a “good” model seen by high adj <span class="math inline">\(R^2\)</span> and significant F-statistic, but no significant predictors, or if you care about what is mostly contributing to the outcome’s variance).<br>
Overall, you should present both the contextualised importance of your findings and the numbers (unstandardised regression coefficients, standardised if makes sense, standard errors, t values, residual standard error, residual df, adjusted <span class="math inline">\(R^2\)</span> if multivariable, CIs and p-values).<br>
All examples here assume you have been through the assessment of your linear model and are happy with it.<br>
For now, outcomes are continuous and the tabs talk about predictors</p>
<section id="continuous-no-scaling" class="level3">
<h3 class="anchored" data-anchor-id="continuous-no-scaling">Continuous, no scaling</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp, <span class="at">data =</span> mtcars))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../images/lm_cont_reporting.png" class="img-fluid figure-img"></p>
<figcaption>Summary output</figcaption>
</figure>
</div>
<ul>
<li>increasing the weight by 1000 lbs would result in a drop of 3.8773 miles/gallon i.e.&nbsp;one unit change of weight results in a drop of 3.8773 miles/gallon<br>
</li>
<li>an increase in 1 horsepower (gross) would result in a drop of 0.03177 miles/gallon i.e.&nbsp;an increase in 100 horsepower (gross) would result in a drop of 3.177 miles/gallon<br>
</li>
<li>the typical prediction would be off by ~2.6 miles/gallon<br>
</li>
<li>the model explains ~81.48% of the variation of miles/gallon, i.e.&nbsp;the adjusted <span class="math inline">\(R^2\)</span> = 0.8148</li>
</ul>
</section>
<section id="mixed-no-scaling" class="level3">
<h3 class="anchored" data-anchor-id="mixed-no-scaling">Mixed, no scaling</h3>
<section id="binary" class="level4">
<h4 class="anchored" data-anchor-id="binary">Binary</h4>
<p>It’s common to have some sort of binary in your predictors, like sex. If it is encoded as 0 and 1, R handles it regardless whether it is a factor or numerical, and the interpretation of its coefficient holds the same in both cases, just different naming, so it is instantly clear which level represented by the coefficient. The underlying equation is <span class="math inline">\(mpg = \beta_0 +  \beta_1*wt + \beta_2*hp + \beta_3*I(vs == 1)\)</span>, where <span class="math inline">\(I()\)</span> is an indicator function, returning 1 when the expression is true, so the reference is the ‘0’ group. In this case vs = 0 means engine is v-shaped, whilst vs = 1 means straight, as long as the levels match the labeled values!</p>
<p><strong>Note:</strong> This also holds when it is any 2 integer values that <em>differ by 1</em>, factor or not (e.g.&nbsp;1,2 or 4,5). If they do not differ by 1, it <strong>has</strong> to be a factor to be treated as a categorical binary (i.e.&nbsp;representing two categories)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> vs, <span class="at">data =</span> mtcars))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + hp + vs, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4667 -1.4857 -0.4296  1.0341  5.7384 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 35.38267    2.42564  14.587 1.31e-14 ***
wt          -3.78003    0.63985  -5.908 2.35e-06 ***
hp          -0.02542    0.01100  -2.312   0.0284 *  
vs           1.36771    1.35296   1.011   0.3207    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.592 on 28 degrees of freedom
Multiple R-squared:  0.8329,    Adjusted R-squared:  0.815 
F-statistic: 46.52 on 3 and 28 DF,  p-value: 5.276e-11</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># "factored" vs, notice vs_f became vs_f1 as a variable, meaning the reference </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># is vs_f0 i.e. the 0 group</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>mtcars_f <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">vs_f =</span> <span class="fu">as.factor</span>(vs))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> vs_f, <span class="at">data =</span> mtcars_f))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + hp + vs_f, data = mtcars_f)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4667 -1.4857 -0.4296  1.0341  5.7384 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 35.38267    2.42564  14.587 1.31e-14 ***
wt          -3.78003    0.63985  -5.908 2.35e-06 ***
hp          -0.02542    0.01100  -2.312   0.0284 *  
vs_f1        1.36771    1.35296   1.011   0.3207    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.592 on 28 degrees of freedom
Multiple R-squared:  0.8329,    Adjusted R-squared:  0.815 
F-statistic: 46.52 on 3 and 28 DF,  p-value: 5.276e-11</code></pre>
</div>
</div>
<p>(Imagine vs is also significant and it makes sense for it to be in the model):</p>
<ul>
<li>increasing the weight by 1000 lbs would result in a drop of 3.78003 miles/gallon i.e.&nbsp;one unit change of weight results in a drop of 3.78003 miles/gallon<br>
</li>
<li>an increase in 1 horsepower (gross) would result in a drop of 0.02542 miles/gallon i.e.&nbsp;an increase in 100 horsepower (gross) would result in a drop of 2.542 miles/gallon<br>
</li>
<li>a straight engine (group 1) has a higher mpg by 1.36771 than v-shaped engines<br>
</li>
<li>the typical prediction would be off by ~2.6 miles/gallon<br>
</li>
<li>the model explains ~81.5% of the variation of miles/gallon, i.e.&nbsp;the adjusted <span class="math inline">\(R^2\)</span> = 0.815</li>
</ul>
</section>
<section id="categorical" class="level4">
<h4 class="anchored" data-anchor-id="categorical">Categorical</h4>
<p>Let’s say a variable has more than 2 levels, e.g.&nbsp;in this dataset, cars can have 4,6, or 8 cylinders. Let’s call each a category (you can make categories by binning the values you have e.g.). This adds k-1 dummy variables to the model, where k is the amount of categories, making the model: <span class="math inline">\(mpg = \beta_0 + \beta_1*wt + \beta_2*hp + \beta_3*I(cyl\_f == 6) + \beta_4*I(cyl\_f == 8)\)</span>,</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>mtcars_f <span class="ot">&lt;-</span> mtcars <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">cyl_f =</span> <span class="fu">as.factor</span>(cyl))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> cyl_f, <span class="at">data =</span> mtcars_f))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + hp + cyl_f, data = mtcars_f)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.2612 -1.0320 -0.3210  0.9281  5.3947 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 35.84600    2.04102  17.563 2.67e-16 ***
wt          -3.18140    0.71960  -4.421 0.000144 ***
hp          -0.02312    0.01195  -1.934 0.063613 .  
cyl_f6      -3.35902    1.40167  -2.396 0.023747 *  
cyl_f8      -3.18588    2.17048  -1.468 0.153705    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.44 on 27 degrees of freedom
Multiple R-squared:  0.8572,    Adjusted R-squared:  0.8361 
F-statistic: 40.53 on 4 and 27 DF,  p-value: 4.869e-11</code></pre>
</div>
</div>
<ul>
<li>increasing the weight by 1000 lbs would result in a drop of 3.18140 miles/gallon i.e.&nbsp;one unit change of weight results in a drop of 3.18140 miles/gallon</li>
<li>an increase in 1 horsepower (gross) would result in a drop of 0.02312 miles/gallon i.e.&nbsp;an increase in 100 horsepower (gross) would result in a drop of 2.312 miles/gallon</li>
<li>our reference group is <code>cyl=4</code>, for us meaning 4 cylinders, so our <code>cyl=6</code> group has a lower mpg by 3.35902</li>
<li>our <code>cyl=8</code> group has a lower mpg than <code>cyl=4</code> by 3.18588, although it is not significantly diff from 0 difference</li>
<li>the typical prediction would be off by 2.44 miles/gallon</li>
<li>the model explains ~83.6% of the variation of miles/gallon, i.e.&nbsp;the adjusted <span class="math inline">\(R^2\)</span> = 0.8361</li>
</ul>
</section>
</section>
<section id="scaling" class="level3">
<h3 class="anchored" data-anchor-id="scaling">Scaling</h3>
<p>The term standardised coefficients refers to coefficients that have been standardised so as to make them comparable with each other (due to different magnitudes and units of independent variables), giving you the information which independent variables explain the dependent variable more. The values are between −1 and +1 and the larger the value, the greater the contribution of the independent variable to explaining the dependent variable. This doesn’t differ between continuous and categorical variables. Another interpretation we get from that is changes per standard deviations instead of per unit changes, for both the outcome and predictor.</p>
<p>The way to standardise coefficients is either run the model with every variable (dependent and independent!) as scaled (mean 0, std 1), or, on each unstandardised coefficient, multiply it by its variable standard deviation and divide by the outcomes standard deviation from the dataset that is <em>used</em> in the model.</p>
<p><strong>Note on standardising categorical vars</strong>: you physically can’t run scaling on a factor, it has to be numerical for that to happen, so if you have a binary, turn the data into 0s and 1s, and if you have a categorical, make the dummy numerical binaries that would be in your model (k-1 of them, excludes reference group!)<br>
You could also do the standardisation manually, but still requires making the dummy variables to, at the very least, extract the sd</p>
<p>There is no intercept when coeffs are standardised!</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>lm_unstd <span class="ot">&lt;-</span> <span class="fu">lm</span>(mpg <span class="sc">~</span> wt <span class="sc">+</span> hp <span class="sc">+</span> vs, <span class="at">data =</span> mtcars)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_unstd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = mpg ~ wt + hp + vs, data = mtcars)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4667 -1.4857 -0.4296  1.0341  5.7384 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 35.38267    2.42564  14.587 1.31e-14 ***
wt          -3.78003    0.63985  -5.908 2.35e-06 ***
hp          -0.02542    0.01100  -2.312   0.0284 *  
vs           1.36771    1.35296   1.011   0.3207    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.592 on 28 degrees of freedom
Multiple R-squared:  0.8329,    Adjusted R-squared:  0.815 
F-statistic: 46.52 on 3 and 28 DF,  p-value: 5.276e-11</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># requires you to have everything numerical in the data</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>QuantPsyc<span class="sc">::</span><span class="fu">lm.beta</span>(lm_unstd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        wt         hp         vs 
-0.6136770 -0.2892039  0.1143775 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># another way to reach them:</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lm_unstd)[<span class="fu">c</span>(<span class="st">"wt"</span>, <span class="st">"hp"</span>, <span class="st">"vs"</span>)]<span class="sc">*</span><span class="fu">c</span>(purrr<span class="sc">::</span><span class="fu">map_dbl</span>(<span class="fu">list</span>(mtcars<span class="sc">$</span>wt, mtcars<span class="sc">$</span>hp, mtcars<span class="sc">$</span>vs), sd))<span class="sc">/</span><span class="fu">sd</span>(mtcars<span class="sc">$</span>mpg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        wt         hp         vs 
-0.6136770 -0.2892039  0.1143775 </code></pre>
</div>
</div>
<ul>
<li>We see wt has the most influence on mpg (decreases, but highest impact)</li>
<li>With one std deviation change of wt (sd(wt) = 0.9784574 * 1000 lbs = 978 lbs), we get a 0.61 std deviation decrease in mpg (sd(mtcars$mpg) = 6.02)</li>
<li>with binary variables, you can only claim the amount of influence it has, since a std of a binary isn’t interpretable</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For interpreting changes:</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>one_std_change_wt <span class="ot">&lt;-</span> <span class="fu">coef</span>(lm_unstd)[<span class="st">"wt"</span>]<span class="sc">*</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">sd</span>(mtcars<span class="sc">$</span>wt)) <span class="sc">+</span> <span class="fu">coef</span>(lm_unstd)[<span class="st">"hp"</span>]<span class="sc">*</span><span class="dv">1</span> <span class="sc">+</span> <span class="fu">coef</span>(lm_unstd)[<span class="st">"vs"</span>]<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>an_instance <span class="ot">&lt;-</span>  <span class="fu">coef</span>(lm_unstd)[<span class="st">"wt"</span>]<span class="sc">*</span><span class="dv">1</span> <span class="sc">+</span> <span class="fu">coef</span>(lm_unstd)[<span class="st">"hp"</span>]<span class="sc">*</span><span class="dv">1</span> <span class="sc">+</span> <span class="fu">coef</span>(lm_unstd)[<span class="st">"vs"</span>]<span class="sc">*</span><span class="dv">1</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(one_std_change_wt <span class="sc">-</span> an_instance, QuantPsyc<span class="sc">::</span><span class="fu">lm.beta</span>(lm_unstd)[<span class="st">"wt"</span>] <span class="sc">*</span> <span class="fu">sd</span>(mtcars<span class="sc">$</span>mpg))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</section>
<section id="categorical-no-scaling" class="level3">
<h3 class="anchored" data-anchor-id="categorical-no-scaling">Categorical, no scaling</h3>
<p>Practically the same as mixed and no scaling. Here we have genetic data. We will examine the association of the actn3_r577x SNP with the percentage change in strength of the non-dominant arm before and after exercise (NDRM.CH). The research team believes that the effect of genotype on our trait might differ between males and females, and we can examine this by including the Gender variable in our analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fms <span class="ot">&lt;-</span> <span class="fu">read.delim</span>(<span class="st">"../../data/FAMuSS_data.txt"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>, <span class="at">sep =</span> <span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>lm.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(NDRM.CH <span class="sc">~</span> <span class="fu">factor</span>(actn3_r577x) <span class="sc">+</span> <span class="fu">factor</span>(Gender), <span class="at">data =</span> fms)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm.fit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = NDRM.CH ~ factor(actn3_r577x) + factor(Gender), 
    data = fms)

Residuals:
    Min      1Q  Median      3Q     Max 
-67.376 -20.295  -3.903  16.691 186.805 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             57.409      2.532  22.673  &lt; 2e-16 ***
factor(actn3_r577x)CT    5.787      3.010   1.923  0.05501 .  
factor(actn3_r577x)TT    9.967      3.360   2.966  0.00314 ** 
factor(Gender)Male     -23.472      2.565  -9.151  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 30.91 on 599 degrees of freedom
  (794 observations deleted due to missingness)
Multiple R-squared:  0.1335,    Adjusted R-squared:  0.1292 
F-statistic: 30.76 on 3 and 599 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li>the genotype is treated as two binary variables that compare the CT and TT genotypes with the CC genotype (treated as the baseline).</li>
<li>for Gender, Female is treated as the baseline so factor(Gender)Male measures the difference between males and females.</li>
<li>the regression model that is specified in R as NDRM.CH ~ factor(actn3_r577x) + factor(Gender) can be written mathematically as: <span class="math inline">\(\small Y=β_0+β_1I(actn3\_r577x=CT)+β_2I(actn3\_r577x=TT)+β_3I(Gender=Male)+ϵ\)</span> where Y is the outcome, <span class="math inline">\(β_0\)</span> is the estimated mean value of the trait for females with the CC genotype</li>
<li>the average percentage change in the non-dominant arm muscle strength is estimated at 57.409 for females with homozygous CC genotype</li>
<li>the effect in females of having the heterozygous CT genotype compared with CC is estimated to be 5.787, but this is not significantly different from zero at <span class="math inline">\(α = 0.05\)</span>.</li>
<li>the effect of TT genotype is estimated to be nearly twice as large (9.9), and is significant</li>
<li>for CC genotype males, the estimated percentage change in the non-dominant arm muscle strength is 57.409 − 23.472</li>
<li>because interaction between gender and genotype is not included in the model, we assume that the effect of genotype on the mean response is the <strong>same in males</strong> as in females, with the CT and TT mean response estimated to be 5.787 and 9.967 higher than for the CC genotype.</li>
</ul>
</section>
<section id="logged-values" class="level3">
<h3 class="anchored" data-anchor-id="logged-values">“Logged” values</h3>
<section id="only-dependent-variable-is-log-transformed" class="level4">
<h4 class="anchored" data-anchor-id="only-dependent-variable-is-log-transformed">Only dependent variable is log-transformed</h4>
<p><span class="math display">\[E(V|x) = E(log(Y)|x) = \beta_0 + \sum_{j=1}^k\beta_jg_{j}(x)\]</span> For one unit change of trait <span class="math inline">\(j\)</span>, it will result in one unit change of <span class="math inline">\(V\)</span>, however you are usually interested in the change in <span class="math inline">\(Y\)</span>, as that is your measured trait.<br>
One unit change of trait <span class="math inline">\(j\)</span> results in <span class="math inline">\((e^{\beta_j} - 1)*100\%\)</span> percent difference (in <strong>geometric mean</strong>) of <span class="math inline">\(Y\)</span>. See math proof below for more information.</p>
</section>
<section id="some-independent-variables-are-log-transformed" class="level4">
<h4 class="anchored" data-anchor-id="some-independent-variables-are-log-transformed">Some independent variables are log-transformed</h4>
<p>E.g. <span class="math inline">\(Y=β_0+β_1x_1+β_2\log(x_2)+β_3\log(x_3)+ϵ\)</span></p>
<p>Let’s say we have <span class="math inline">\(x_3\)</span> be <span class="math inline">\(r_1\)</span>, and it changes to <span class="math inline">\(r_2\)</span>:</p>
<p>The effects of the log transformed traits are still linear, so <span class="math inline">\(E(Y|r_2) -  E(Y|r_1) = \beta_3 \times [ \log(r_2) – \log(r_1) ] = \beta_3 \times [\log(r_2 / r_1)]\)</span>;<br>
Reporting this would be e.g.&nbsp;a 1% increase in x_3 leads to <span class="math inline">\(log1.01 \times \beta_3\)</span> unit increase in <span class="math inline">\(Y \rightarrow\)</span> which can be approximated (because it’s a small change) by <span class="math inline">\(0.01*\beta_3 \text{ or } \frac{\beta_3}{100}\)</span></p>
</section>
<section id="dependent-and-some-independent-are-log-transformed" class="level4">
<h4 class="anchored" data-anchor-id="dependent-and-some-independent-are-log-transformed">Dependent and some independent are log-transformed</h4>
<p>The situation we haven’t covered yet is reporting an increase in a log-transformed independent for a log-transformed dependent.</p>
<p><span class="math display">\[
\begin{gather}
E(\log(Y)|r_2) - E(\log(Y)|r_1) = \beta_3 \times [ \log(r_2) - \log(r_1) ] = \beta_3 \times [\log(r_2 / r_1)] \iff \\
\frac{e^{E(\log(Y)|r_2)}}{e^{E(\log(Y)|r_1)}} = e^{\log((\frac{r_2}{r_1})^{\beta_3})} \iff \frac{\text{GeomMean}(Y|r_2)}{\text{GeomMean}(Y|r_1)}= \left(\frac{r_2}{r_1}\right)^{\beta_3}
\end{gather}
\]</span></p>
<p>So for a 1% increase in <span class="math inline">\(x_3\)</span> leads to <span class="math inline">\((1.01^{\beta_3}-1)*100\%\)</span> percent change in the geometric mean of <span class="math inline">\(Y \rightarrow\)</span> which can be approximated (because it’s a small change) by <span class="math inline">\(0.01*\beta_3 * 100 \% = \beta_3 \%\)</span>. Another way to report it would be that for each twofold increase in <span class="math inline">\(x_3\)</span> leads to <span class="math inline">\((2^{\beta_3}-1)*100\%\)</span> percent difference (in <strong>geometric mean</strong>) of Y.</p>
</section>
<section id="math-proof" class="level4">
<h4 class="anchored" data-anchor-id="math-proof">Math proof:</h4>
<p>You want a function of Y, not of logY:<br>
<span class="math display">\[
\begin{gather}
\mathbf{x} - \text{realisation of predictors} \\
\mathbf{x_j} - \text{realisation of predictors like } \mathbf{x} \text{ where only } x_j \text{ is increased by 1 unit}\\
E(log(Y)|\mathbf{x_j}) -  E(log(Y)|\mathbf{x}) = \beta_j \iff e^{E(log(Y)|\mathbf{x_j}) -  E(log(Y)|\mathbf{x})} = e^{\beta_j} \iff \\
\frac{e^{E(log(Y)|\mathbf{x_j})}}{e^{E(log(Y)|\mathbf{x})}} = e^{\beta_j}  \iff \frac{GeomMean(Y|\mathbf{x_j})}{GeomMean(Y|\mathbf{x})}= e^{\beta_j}
\end{gather}
\]</span> Taking the exponent of the average log is the definition of a geometric mean: <span class="math display">\[ e^{E(logY|x)} = e^{\frac{1}{n}(log(y_1) + .. +log(y_n))} = e^{\frac{1}{n}(log(y_1*..*y_n))} = e^{log((y_1*..*y_n)^\frac{1}{n})} = (y_1*..*y_n)^\frac{1}{n} \rightarrow \text{geometric mean} \]</span></p>
</section>
</section>
<section id="changing-from-unit-to-percentile" class="level3">
<h3 class="anchored" data-anchor-id="changing-from-unit-to-percentile">Changing from unit to percentile</h3>
<p>To report moving from the x<sup>th</sup> to the y<sup>th</sup> percentile:<br>
Calculate the value of your predictor at both percentiles, find the difference, and multiply that difference by the coefficient: <span class="math inline">\(\beta _{\text{y-x}}=\beta _{\text{raw}}\times (q_{y\%,pred} - q_{x\%,pred})\)</span></p>
</section>
</div>
<div id="tabset-1-7" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-7-tab">
<section id="r-caveatsdefaults-i-need-to-know-about" class="level3">
<h3 class="anchored" data-anchor-id="r-caveatsdefaults-i-need-to-know-about">R caveats/defaults I need to know about?</h3>
<ul>
<li>uses ordinary least squares which doesn’t assume any distribution for <span class="math inline">\(Y_i\)</span></li>
<li>implied intercept term unless you tell it otherwise</li>
<li>Non-NULL weights can be used to indicate that different observations have different variances (<span class="math inline">\(\epsilon_i\)</span>), see more in <a href="https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/lm">details then</a></li>
<li>factor/categorical/continuous in the formula might change what the null is, hence what statistically different actually means - see Anova f-test in testing TBA</li>
</ul>
</section>
</div>
<div id="tabset-1-8" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-8-tab">
<section id="what-can-you-use-it-for-now" class="level3">
<h3 class="anchored" data-anchor-id="what-can-you-use-it-for-now">What can you use it for now?</h3>
<p>You can use it for predicting, now for a given <span class="math inline">\(x_i\)</span> you care about, determine a <span class="math inline">\(Y_i\)</span></p>
</section>
</div>
<div id="tabset-1-9" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-9-tab">
<section id="if-you-want-the-maths-behind-it" class="level3">
<h3 class="anchored" data-anchor-id="if-you-want-the-maths-behind-it">If you want the maths behind it</h3>
<p>How is <span class="math inline">\(m(x)\)</span> an additive function? We know <span class="math inline">\(m(x) = \beta_0 + \sum_{i=1}^k \beta_ig_{i}(x)\)</span>. Let’s define <span class="math inline">\(f_{v_1}(x) = \beta_0 + \sum_{i=1}^k \beta_ig_{i}(x),\text{ where } v_1 = (\beta_0, \beta_1, ..., \beta_k)\)</span>; we need <span class="math inline">\(f_{v_1+v_2}(x) = f_{v_1}(x) + f_{v_2}(x), \text{ and } \\ f_{c*v_1}(x) = c*f_{v_1}(x)\)</span> to hold true.</p>
<p>Proof: <span class="math display">\[
\begin{gather*}
f_{v_1}(x) = \beta_0 + \sum_{i=1}^k \beta_ig_{i}(x), ~ f_{v_2}(x) = \alpha_0 + \sum_{i=1}^k \alpha_ig_{i}(x) \text{  and } \\ v_1 = (\beta_0, \beta_1, ..., \beta_k), ~ v_2 = (\alpha_0, \alpha_1, ..., \alpha_k) \implies \\
v1+v2 = (\beta_0 + \alpha_0, \beta_1 + \alpha_1, ..., \beta_k + \alpha_k) \implies \\
f_{v_1+v_2}(x) = (\beta_0 + \alpha_0) + \sum_{i=1}^k (\beta_i+\alpha_i)g_{i}(x) = \beta_0  + \sum_{i=1}^k \beta_ig_{i}(x) + \alpha_0 + \sum_{i=1}^k \alpha_ig_{i}(x) = f_{v_1}(x) + f_{v_2}(x) ~ \square \\
c*v1 = (c*\beta_0, c*\beta_1, ..., c*\beta_k) \implies \\
f_{c*v_1}(x) = c*\beta_0 + \sum_{i=1}^k (c*\beta_i)g_{i}(x) = c*\beta_0 + c*\sum_{i=1}^k \beta_ig_{i}(x) = c(\beta_0 + \sum_{i=1}^k \beta_ig_{i}(x)) = c*f_{v_1}(x) ~ \square
\end{gather*}
\]</span></p>
</section>
</div>
</div>
</div>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div style="font-size: 50%;">
<ol type="1">
<li>My uni notes from <a href="https://handbook.unimelb.edu.au/2023/subjects/mast20005">Statistics (MAST20005)</a> and <a href="https://handbook.unimelb.edu.au/2024/subjects/binf90001">Statistics for Bioinformatics (BINF90001)</a></li>
<li>Roustaei N. Application and interpretation of linear-regression analysis. Med Hypothesis Discov Innov Ophthalmol. 2024 Oct 14;13(3):151-159. doi: 10.51329/mehdiophthal1506. PMID: 39507810; PMCID: PMC11537238. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11537238/">https://pmc.ncbi.nlm.nih.gov/articles/PMC11537238/</a></li>
<li><a href="https://r-statistics.co/Interpreting-Regression-Output-Completely.html">https://r-statistics.co/Interpreting-Regression-Output-Completely.html</a></li>
<li><a href="https://numiqo.com/tutorial/linear-regression">https://numiqo.com/tutorial/linear-regression</a></li>
<li><a href="https://library.virginia.edu/data/articles/addressing-multicollinearity">https://library.virginia.edu/data/articles/addressing-multicollinearity</a></li>
<li>Jones L, Barnett A, Vagenas D. Linear regression reporting practices for health researchers, a cross-sectional meta-research study. PLoS One. 2025 Mar 20;20(3):e0305150. doi: 10.1371/journal.pone.0305150. PMID: 40111967; PMCID: PMC11925299. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11925299/">https://pmc.ncbi.nlm.nih.gov/articles/PMC11925299/</a></li>
<li>Jones L, Barnett A, Vagenas D. Common misconceptions held by health researchers when interpreting linear regression assumptions, a cross-sectional study. PLoS One. 2025 Jun 5;20(6):e0299617. doi: 10.1371/journal.pone.0299617. PMID: 40471888; PMCID: PMC12140278. <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0299617">https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0299617</a></li>
<li><a href="https://www.statology.org/interpret-regression-output-in-r/">https://www.statology.org/interpret-regression-output-in-r/</a></li>
<li><a href="https://feliperego.github.io/blog/2015/10/23/Interpreting-Model-Output-In-R">https://feliperego.github.io/blog/2015/10/23/Interpreting-Model-Output-In-R</a></li>
<li>Hidalgo B, Goodman M. Multivariate or multivariable regression? Am J Public Health. 2013 Jan;103(1):39-40. doi: 10.2105/AJPH.2012.300897. Epub 2012 Nov 15. PMID: 23153131; PMCID: PMC3518362. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC3518362/">https://pmc.ncbi.nlm.nih.gov/articles/PMC3518362/</a></li>
</ol>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/KatStan\.github\.io\/stats-knowledge\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>